---
- name: new_users
  ansible.builtin.user:
    name: "{{ new_users }}"
    comment: "{{ comments }}"
    uid: "{{ useruid }}"
    group: "{{ group }}"
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"